baseURL = "https://maxturgeon.ca/w21-sci2000/"
languageCode = "en-ca"
title = "SCI 2000 - Winter 2021"
theme = "book"
ignoreFiles = ["_files$", "_cache$"]

[params]
BookMenuBundle = "/menu"
BookToC = false
BookSearch = false
